### ISSUE TITLE
SD Card Installer Greyed Out

### ISSUE THREAD

**Issue by wolfpacleader1986** [MiSTer-devel/SD-Installer-Win64_MiSTer#5]
Trying to create my MiSTer MicroSD card on my Windows 10 PC and every time I start it, everything is greyed out and won’t let me start or select anything. Using the latest installer and latest MiSTer build.

**Comment by wolfpacleader1986** [comment]
Tried it with Windows 10 on the other PC(which was a recent installation so no real major updates), and after it downloaded Net Framework 3.5, it worked. So something in the newer Windows updates must've broken it.

**Comment by sorgelig** [comment]
I've just recently re-installed the fresh Win10 on my PC with all updates. SD Installer works fine.
Is your Win10 64bit?

**Comment by wolfpacleader1986** [comment]
Yes

**Comment by sorgelig** [comment]
Then it's because of specific driver of that SD reader. Try other SD reader. Some apps may install additional filter driver to all USB devices preventing it work correctly. This is what happened to my computer sometime ago causing PC hang if i insert SD formatted for MiSTer. So i had to re-install Windows 10 from scratch. Even re-install on top of existing Windows 10 didn't help.
